import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import {
  GENERATED_DIR_NAME,
  resolveGeneratedDir,
  writeGeneratedFiles,
} from './iosExport';
import type { IosProject } from './iosBuild';

function project(partial?: Partial<IosProject>): IosProject {
  return {
    projectPath: '/repo/MyApp.xcodeproj',
    projectKind: 'project',
    scheme: 'MyApp',
    bundleId: 'com.example.myapp',
    configurations: ['Debug', 'Release'],
    ...partial,
  };
}

const FS_SYNCED_PBXPROJ = `// !$*UTF8*$!
{
  objects = {
    ABC123 /* MyApp */ = { isa = PBXFileSystemSynchronizedRootGroup; path = MyApp; };
  };
}`;

const LEGACY_PBXPROJ = `// !$*UTF8*$!
{
  objects = {
    ABC123 /* MyApp */ = { isa = PBXGroup; children = (); path = MyApp; };
  };
}`;

describe('resolveGeneratedDir', () => {
  const reader = (content: Record<string, string>) => async (p: string) => {
    if (p in content) return content[p];
    throw new Error(`ENOENT: ${p}`);
  };
  const existsIn = (paths: string[]) => async (p: string) => paths.includes(p);

  it('targets <stem>/TangoGenerated and detects fs-synced projects', async () => {
    const result = await resolveGeneratedDir(
      project(),
      reader({ '/repo/MyApp.xcodeproj/project.pbxproj': FS_SYNCED_PBXPROJ }),
      existsIn(['/repo/MyApp']),
    );
    expect(result.dir).toBe(`/repo/MyApp/${GENERATED_DIR_NAME}`);
    expect(result.inclusion).toBe('fs-synced');
  });

  it('reports manual-add-required for legacy PBXGroup projects', async () => {
    const result = await resolveGeneratedDir(
      project(),
      reader({ '/repo/MyApp.xcodeproj/project.pbxproj': LEGACY_PBXPROJ }),
      existsIn(['/repo/MyApp']),
    );
    expect(result.inclusion).toBe('manual-add-required');
  });

  it('resolves the sibling .xcodeproj for workspaces', async () => {
    const result = await resolveGeneratedDir(
      project({ projectPath: '/repo/MyApp.xcworkspace', projectKind: 'workspace' }),
      reader({ '/repo/MyApp.xcodeproj/project.pbxproj': FS_SYNCED_PBXPROJ }),
      existsIn(['/repo/MyApp']),
    );
    expect(result.dir).toBe(`/repo/MyApp/${GENERATED_DIR_NAME}`);
    expect(result.inclusion).toBe('fs-synced');
  });

  it('falls back to the scheme dir, then the project dir', async () => {
    const byScheme = await resolveGeneratedDir(
      project({ scheme: 'AppScheme' }),
      reader({}),
      existsIn(['/repo/AppScheme']),
    );
    expect(byScheme.dir).toBe(`/repo/AppScheme/${GENERATED_DIR_NAME}`);

    const fallback = await resolveGeneratedDir(project(), reader({}), existsIn([]));
    expect(fallback.dir).toBe(`/repo/${GENERATED_DIR_NAME}`);
    expect(fallback.inclusion).toBe('manual-add-required');
  });

  it('never claims fs-synced when files land outside a synced source root', async () => {
    // pbxproj is fs-synced, but the source-root folder doesn't exist so files
    // would land next to the project — manual wiring required.
    const result = await resolveGeneratedDir(
      project(),
      reader({ '/repo/MyApp.xcodeproj/project.pbxproj': FS_SYNCED_PBXPROJ }),
      existsIn([]),
    );
    expect(result.inclusion).toBe('manual-add-required');
  });
});

describe('writeGeneratedFiles', () => {
  let dir: string;

  beforeEach(async () => {
    dir = await fs.mkdtemp(path.join(os.tmpdir(), 'tango-gen-'));
  });

  afterEach(async () => {
    await fs.rm(dir, { recursive: true, force: true });
  });

  const marked = (name: string) =>
    `// Generated by tango — DO NOT EDIT.\n// tango:generated v=1 screen=${name}\n// x\n\nstruct X {}\n`;

  it('writes all files', async () => {
    await writeGeneratedFiles(dir, [
      { path: 'A.swift', content: marked('a') },
      { path: 'B.swift', content: marked('b') },
    ]);
    expect((await fs.readdir(dir)).sort()).toEqual(['A.swift', 'B.swift']);
  });

  it('deletes stale tango-marked files absent from the new set', async () => {
    await writeGeneratedFiles(dir, [{ path: 'Old.swift', content: marked('old') }]);
    await writeGeneratedFiles(dir, [{ path: 'New.swift', content: marked('new') }]);
    expect(await fs.readdir(dir)).toEqual(['New.swift']);
  });

  it('never deletes unmarked files', async () => {
    await fs.writeFile(path.join(dir, 'UserCode.swift'), 'struct Mine {}\n');
    await writeGeneratedFiles(dir, [{ path: 'New.swift', content: marked('new') }]);
    expect((await fs.readdir(dir)).sort()).toEqual(['New.swift', 'UserCode.swift']);
  });
});
