import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';

// The directory Claude operates in: where the in-app terminal lands, where
// `.mcp.json` lives so the `claude` CLI auto-discovers our canvas tools, and
// where `design-scratch/` PNGs land for the "Send to Claude" flow.
//
// Kept distinct from the tango repo on purpose — this lets you develop tango
// locally without your dev shell stepping on Claude's working tree.
//
// Override with TANGO_WORKSPACE=/some/path.

export const WORKSPACE_DIR = process.env.TANGO_WORKSPACE
  ? path.resolve(process.env.TANGO_WORKSPACE)
  : path.join(os.homedir(), 'dev', 'tangotest');

const MCP_CONFIG_PATH = path.join(WORKSPACE_DIR, '.mcp.json');
const CLAUDE_SETTINGS_PATH = path.join(WORKSPACE_DIR, '.claude', 'settings.json');
const CLAUDE_MD_PATH = path.join(WORKSPACE_DIR, 'CLAUDE.md');

// Settings we always want present in the workspace's Claude Code config.
// Merged into whatever's already in settings.json — we don't clobber unrelated
// keys or hooks the user has set.
const REQUIRED_CLAUDE_ENV = {
  CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS: '1',
} as const;

// Always overwrite — the tango app owns this file. It documents the
// canvas MCP tools so Claude knows the seam exists and uses it for visual work.
const CLAUDE_MD = `# Designer canvas (tango)

You're running inside the **tango** workspace. The user is viewing an Excalidraw canvas in the left pane of their browser; this terminal is in the right pane. The \`tango-canvas\` MCP server lets you read and modify that canvas:

- \`get_canvas_state\` — read the current scene (elements + appState; embedded image bytes elided)
- \`set_canvas_state\` — replace the entire scene
- \`add_elements\` — append elements without disturbing existing ones
- \`clear_canvas\` — empty the scene
- \`screenshot_canvas\` — see the rendered canvas as an image (call this before proposing wireframes, critiques, or anything that depends on what the user has drawn — \`get_canvas_state\` strips embedded image bytes, this gives you the actual pixels)

Reach for these whenever the user asks for visual work — wireframes, diagrams, sketches, layout proposals. Prefer \`add_elements\` when annotating or extending; \`set_canvas_state\` for a full redesign. Element shape matches Excalidraw's \`serializeAsJSON\` output — call \`get_canvas_state\` first if you need to see the shape.

Edits via these tools appear on the user's canvas immediately. The user can \`Cmd+Z\` your changes, and their edits flow back so \`get_canvas_state\` always reflects what's on their screen right now.

For visual context, prefer \`screenshot_canvas\` — it's the live channel. The user may also drop a PNG into \`design-scratch/\` and ping you with a \`# review design at design-scratch/...png\` comment line; that's the deliberate-handoff channel — read the file when they point you at it.

---

This \`CLAUDE.md\` is generated by tango and overwritten on each server boot. Don't hand-edit — put project-specific instructions in a separate file.
`;

// Always overwrite — the tango app owns this file and it has to point at the
// running server. If the user has hand-edited it we'd rather they keep their
// edit somewhere else; this is generated config.
function mcpConfig(port: number): string {
  return JSON.stringify(
    {
      mcpServers: {
        'tango-canvas': {
          type: 'http',
          url: `http://localhost:${port}/mcp`,
        },
      },
    },
    null,
    2,
  ) + '\n';
}

async function readJsonOrEmpty(p: string): Promise<Record<string, unknown>> {
  try {
    const raw = await fs.readFile(p, 'utf8');
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed)
      ? (parsed as Record<string, unknown>)
      : {};
  } catch {
    return {};
  }
}

async function writeIfChanged(p: string, next: string): Promise<void> {
  let prev: string | null = null;
  try {
    prev = await fs.readFile(p, 'utf8');
  } catch {
    // missing — fall through to write
  }
  if (prev !== next) {
    await fs.writeFile(p, next);
  }
}

async function ensureClaudeSettings(): Promise<void> {
  const dir = path.dirname(CLAUDE_SETTINGS_PATH);
  await fs.mkdir(dir, { recursive: true });
  const current = await readJsonOrEmpty(CLAUDE_SETTINGS_PATH);
  const env = (current.env && typeof current.env === 'object' && !Array.isArray(current.env)
    ? (current.env as Record<string, unknown>)
    : {}) as Record<string, unknown>;
  const merged = { ...current, env: { ...env, ...REQUIRED_CLAUDE_ENV } };
  await writeIfChanged(CLAUDE_SETTINGS_PATH, JSON.stringify(merged, null, 2) + '\n');
}

export async function ensureWorkspace(port: number): Promise<void> {
  await fs.mkdir(WORKSPACE_DIR, { recursive: true });
  await fs.mkdir(path.join(WORKSPACE_DIR, 'design-scratch'), { recursive: true });
  await writeIfChanged(MCP_CONFIG_PATH, mcpConfig(port));
  await writeIfChanged(CLAUDE_MD_PATH, CLAUDE_MD);
  await ensureClaudeSettings();
}
