// Created by tango from the design screen "Shapes".
// The body below is design-managed (tango:body marker) and is regenerated by
// every Export & Run; the rest of this file is yours.

import SwiftUI

/// Shapes — 390×844
struct ShapesScreen: View {
  var body: some View {
    // tango:body v=1 screen=shapes — managed by tango; edit the design on the canvas (Export & Run regenerates this body)
    ZStack(alignment: .topLeading) {
      Rectangle()
        .fill(Color(red: 0.93333, green: 0.90588, blue: 0.85098, opacity: 1))
        .frame(width: 160, height: 120)
        .offset(x: 24, y: 24)
      RoundedRectangle(cornerRadius: 14)
        .fill(Color(red: 0.38039, green: 0.34902, blue: 0.88235, opacity: 1))
        .overlay(RoundedRectangle(cornerRadius: 14).strokeBorder(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1), lineWidth: 2))
        .frame(width: 160, height: 120)
        .offset(x: 200, y: 24)
      Ellipse()
        .fill(Color(red: 0.5451, green: 0.82353, blue: 0.72549, opacity: 1))
        .overlay(Ellipse().strokeBorder(Color(red: 0.82353, green: 0.84314, blue: 0.89804, opacity: 1), style: StrokeStyle(lineWidth: 1, dash: [4])))
        .frame(width: 120, height: 80)
        .offset(x: 24, y: 170)
      Path { p in
        p.move(to: CGPoint(x: 0, y: 4))
        p.addLine(to: CGPoint(x: 200, y: 4))
      }
        .stroke(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1), style: StrokeStyle(lineWidth: 2, lineCap: .round, lineJoin: .round))
        .frame(width: 200, height: 8)
        .offset(x: 24, y: 280)
      Path { p in
        p.move(to: CGPoint(x: 0, y: 90))
        p.addLine(to: CGPoint(x: 120, y: 0))
      }
        .stroke(Color(red: 0.9451, green: 0.28627, blue: 0.55294, opacity: 1), style: StrokeStyle(lineWidth: 4, lineCap: .round, lineJoin: .round, dash: [4]))
        .frame(width: 120, height: 90)
        .offset(x: 24, y: 300)
      ZStack(alignment: .topLeading) {
        Path { p in
          p.move(to: CGPoint(x: 0, y: 0))
          p.addLine(to: CGPoint(x: 200, y: 60))
        }
          .stroke(Color(red: 0.38039, green: 0.34902, blue: 0.88235, opacity: 1), style: StrokeStyle(lineWidth: 2, lineCap: .round, lineJoin: .round))
        Path { p in
          p.move(to: CGPoint(x: 194.31, y: 54.37))
          p.addLine(to: CGPoint(x: 200, y: 60))
          p.addLine(to: CGPoint(x: 192.16, y: 61.57))
        }
          .stroke(Color(red: 0.38039, green: 0.34902, blue: 0.88235, opacity: 1), style: StrokeStyle(lineWidth: 2, lineCap: .round, lineJoin: .round))
      }
        .frame(width: 200, height: 60)
        .offset(x: 24, y: 420)
      Path { p in
        p.move(to: CGPoint(x: 60, y: 0))
        p.addLine(to: CGPoint(x: 120, y: 104))
        p.addLine(to: CGPoint(x: 0, y: 104))
        p.closeSubpath()
      }
        .fill(Color(red: 0.94902, green: 0.56078, blue: 0.16078, opacity: 1))
        .frame(width: 120, height: 104)
        .offset(x: 24, y: 520)
      Path { p in
        p.move(to: CGPoint(x: 60, y: 0))
        p.addLine(to: CGPoint(x: 74.11, y: 40.58))
        p.addLine(to: CGPoint(x: 117.06, y: 41.46))
        p.addLine(to: CGPoint(x: 82.83, y: 67.42))
        p.addLine(to: CGPoint(x: 95.27, y: 108.54))
        p.addLine(to: CGPoint(x: 60, y: 84))
        p.addLine(to: CGPoint(x: 24.73, y: 108.54))
        p.addLine(to: CGPoint(x: 37.17, y: 67.42))
        p.addLine(to: CGPoint(x: 2.94, y: 41.46))
        p.addLine(to: CGPoint(x: 45.89, y: 40.58))
        p.closeSubpath()
      }
        .fill(Color(red: 0.38039, green: 0.34902, blue: 0.88235, opacity: 0.6))
        .overlay(Path { p in
        p.move(to: CGPoint(x: 60, y: 0))
        p.addLine(to: CGPoint(x: 74.11, y: 40.58))
        p.addLine(to: CGPoint(x: 117.06, y: 41.46))
        p.addLine(to: CGPoint(x: 82.83, y: 67.42))
        p.addLine(to: CGPoint(x: 95.27, y: 108.54))
        p.addLine(to: CGPoint(x: 60, y: 84))
        p.addLine(to: CGPoint(x: 24.73, y: 108.54))
        p.addLine(to: CGPoint(x: 37.17, y: 67.42))
        p.addLine(to: CGPoint(x: 2.94, y: 41.46))
        p.addLine(to: CGPoint(x: 45.89, y: 40.58))
        p.closeSubpath()
      }.stroke(Color(red: 0.38039, green: 0.34902, blue: 0.88235, opacity: 1), style: StrokeStyle(lineWidth: 1, lineCap: .round, lineJoin: .round)))
        .frame(width: 120, height: 120)
        .offset(x: 180, y: 520)
      Path { p in
        p.move(to: CGPoint(x: 50, y: 0))
        p.addLine(to: CGPoint(x: 57.65, y: 31.52))
        p.addLine(to: CGPoint(x: 85.36, y: 14.64))
        p.addLine(to: CGPoint(x: 68.48, y: 42.35))
        p.addLine(to: CGPoint(x: 100, y: 50))
        p.addLine(to: CGPoint(x: 68.48, y: 57.65))
        p.addLine(to: CGPoint(x: 85.36, y: 85.36))
        p.addLine(to: CGPoint(x: 57.65, y: 68.48))
        p.addLine(to: CGPoint(x: 50, y: 100))
        p.addLine(to: CGPoint(x: 42.35, y: 68.48))
        p.addLine(to: CGPoint(x: 14.64, y: 85.36))
        p.addLine(to: CGPoint(x: 31.52, y: 57.65))
        p.addLine(to: CGPoint(x: 0, y: 50))
        p.addLine(to: CGPoint(x: 31.52, y: 42.35))
        p.addLine(to: CGPoint(x: 14.64, y: 14.64))
        p.addLine(to: CGPoint(x: 42.35, y: 31.52))
        p.closeSubpath()
      }
        .fill(LinearGradient(stops: [.init(color: Color(red: 0.38824, green: 0.35686, blue: 1, opacity: 1), location: 0), .init(color: Color(red: 0, green: 0.83137, blue: 1, opacity: 1), location: 1)], startPoint: UnitPoint(x: 0.146, y: 0.146), endPoint: UnitPoint(x: 0.854, y: 0.854)))
        .frame(width: 100, height: 100)
        .opacity(0.9)
        .offset(x: 24, y: 660)
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(red: 0.96078, green: 0.93333, blue: 0.87843, opacity: 1))
    .clipped()
  }
}

#Preview {
  ShapesScreen()
}
