// Generated by tango — DO NOT EDIT.
// tango:generated v=1 screen=shapes
// Regenerated on every "Export & Run"; change the design in tango instead.

import SwiftUI

/// Shapes — 390×844
struct TangoShapesScreen: View {
  var body: some View {
    ZStack(alignment: .topLeading) {
      Rectangle()
        .fill(Color(tangoR: 238, g: 231, b: 217, a: 1))
        .frame(width: 160, height: 120)
        .offset(x: 24, y: 24)
      RoundedRectangle(cornerRadius: 14)
        .fill(Color(tangoR: 97, g: 89, b: 225, a: 1))
        .overlay(RoundedRectangle(cornerRadius: 14).strokeBorder(Color(tangoR: 10, g: 18, b: 53, a: 1), lineWidth: 2))
        .frame(width: 160, height: 120)
        .offset(x: 200, y: 24)
      Ellipse()
        .fill(Color(tangoR: 139, g: 210, b: 185, a: 1))
        .overlay(Ellipse().strokeBorder(Color(tangoR: 210, g: 215, b: 229, a: 1), style: StrokeStyle(lineWidth: 1, dash: [4])))
        .frame(width: 120, height: 80)
        .offset(x: 24, y: 170)
      Path { p in
        p.move(to: CGPoint(x: 0, y: 4))
        p.addLine(to: CGPoint(x: 200, y: 4))
      }
        .stroke(Color(tangoR: 10, g: 18, b: 53, a: 1), style: StrokeStyle(lineWidth: 2, lineCap: .round, lineJoin: .round))
        .frame(width: 200, height: 8)
        .offset(x: 24, y: 280)
      Path { p in
        p.move(to: CGPoint(x: 0, y: 90))
        p.addLine(to: CGPoint(x: 120, y: 0))
      }
        .stroke(Color(tangoR: 241, g: 73, b: 141, a: 1), style: StrokeStyle(lineWidth: 4, lineCap: .round, lineJoin: .round, dash: [4]))
        .frame(width: 120, height: 90)
        .offset(x: 24, y: 300)
      ZStack(alignment: .topLeading) {
        Path { p in
          p.move(to: CGPoint(x: 0, y: 0))
          p.addLine(to: CGPoint(x: 200, y: 60))
        }
          .stroke(Color(tangoR: 97, g: 89, b: 225, a: 1), style: StrokeStyle(lineWidth: 2, lineCap: .round, lineJoin: .round))
        Path { p in
          p.move(to: CGPoint(x: 194.31, y: 54.37))
          p.addLine(to: CGPoint(x: 200, y: 60))
          p.addLine(to: CGPoint(x: 192.16, y: 61.57))
        }
          .stroke(Color(tangoR: 97, g: 89, b: 225, a: 1), style: StrokeStyle(lineWidth: 2, lineCap: .round, lineJoin: .round))
      }
        .frame(width: 200, height: 60)
        .offset(x: 24, y: 420)
      Path { p in
        p.move(to: CGPoint(x: 60, y: 0))
        p.addLine(to: CGPoint(x: 120, y: 104))
        p.addLine(to: CGPoint(x: 0, y: 104))
        p.closeSubpath()
      }
        .fill(Color(tangoR: 242, g: 143, b: 41, a: 1))
        .frame(width: 120, height: 104)
        .offset(x: 24, y: 520)
      Path { p in
        p.move(to: CGPoint(x: 60, y: 0))
        p.addLine(to: CGPoint(x: 74.11, y: 40.58))
        p.addLine(to: CGPoint(x: 117.06, y: 41.46))
        p.addLine(to: CGPoint(x: 82.83, y: 67.42))
        p.addLine(to: CGPoint(x: 95.27, y: 108.54))
        p.addLine(to: CGPoint(x: 60, y: 84))
        p.addLine(to: CGPoint(x: 24.73, y: 108.54))
        p.addLine(to: CGPoint(x: 37.17, y: 67.42))
        p.addLine(to: CGPoint(x: 2.94, y: 41.46))
        p.addLine(to: CGPoint(x: 45.89, y: 40.58))
        p.closeSubpath()
      }
        .fill(Color(tangoR: 97, g: 89, b: 225, a: 0.6))
        .overlay(Path { p in
        p.move(to: CGPoint(x: 60, y: 0))
        p.addLine(to: CGPoint(x: 74.11, y: 40.58))
        p.addLine(to: CGPoint(x: 117.06, y: 41.46))
        p.addLine(to: CGPoint(x: 82.83, y: 67.42))
        p.addLine(to: CGPoint(x: 95.27, y: 108.54))
        p.addLine(to: CGPoint(x: 60, y: 84))
        p.addLine(to: CGPoint(x: 24.73, y: 108.54))
        p.addLine(to: CGPoint(x: 37.17, y: 67.42))
        p.addLine(to: CGPoint(x: 2.94, y: 41.46))
        p.addLine(to: CGPoint(x: 45.89, y: 40.58))
        p.closeSubpath()
      }.stroke(Color(tangoR: 97, g: 89, b: 225, a: 1), style: StrokeStyle(lineWidth: 1, lineCap: .round, lineJoin: .round)))
        .frame(width: 120, height: 120)
        .offset(x: 180, y: 520)
      Path { p in
        p.move(to: CGPoint(x: 50, y: 0))
        p.addLine(to: CGPoint(x: 57.65, y: 31.52))
        p.addLine(to: CGPoint(x: 85.36, y: 14.64))
        p.addLine(to: CGPoint(x: 68.48, y: 42.35))
        p.addLine(to: CGPoint(x: 100, y: 50))
        p.addLine(to: CGPoint(x: 68.48, y: 57.65))
        p.addLine(to: CGPoint(x: 85.36, y: 85.36))
        p.addLine(to: CGPoint(x: 57.65, y: 68.48))
        p.addLine(to: CGPoint(x: 50, y: 100))
        p.addLine(to: CGPoint(x: 42.35, y: 68.48))
        p.addLine(to: CGPoint(x: 14.64, y: 85.36))
        p.addLine(to: CGPoint(x: 31.52, y: 57.65))
        p.addLine(to: CGPoint(x: 0, y: 50))
        p.addLine(to: CGPoint(x: 31.52, y: 42.35))
        p.addLine(to: CGPoint(x: 14.64, y: 14.64))
        p.addLine(to: CGPoint(x: 42.35, y: 31.52))
        p.closeSubpath()
      }
        .fill(LinearGradient(stops: [.init(color: Color(tangoR: 99, g: 91, b: 255, a: 1), location: 0), .init(color: Color(tangoR: 0, g: 212, b: 255, a: 1), location: 1)], startPoint: UnitPoint(x: 0.146, y: 0.146), endPoint: UnitPoint(x: 0.854, y: 0.854)))
        .frame(width: 100, height: 100)
        .opacity(0.9)
        .offset(x: 24, y: 660)
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(tangoR: 245, g: 238, b: 224, a: 1))
    .clipped()
  }
}

#Preview {
  TangoShapesScreen()
}
