// Created by tango from the design screen "Dashboard".
// The body below is design-managed (tango:body marker) and is regenerated by
// every Export & Run; the rest of this file is yours.

import SwiftUI

/// Dashboard — 390×844
struct DashboardScreen: View {
  var body: some View {
    // tango:body v=1 screen=dashboard — managed by tango; edit the design on the canvas (Export & Run regenerates this body)
    ZStack(alignment: .topLeading) {
      Text("Dashboard")
        .font(.system(size: 24, weight: .semibold, design: .serif))
        .foregroundColor(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1))
        .frame(width: 342, height: 40, alignment: .topLeading)
        .offset(x: 24, y: 60)
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(red: 0.96078, green: 0.93333, blue: 0.87843, opacity: 1))
    .clipped()
  }
}

#Preview {
  DashboardScreen()
}
