// Created by tango from the design screen "Login".
// The body below is design-managed (tango:body marker) and is regenerated by
// every Export & Run; the rest of this file is yours.

import SwiftUI

/// Login — 390×844
struct LoginScreen: View {
  var body: some View {
    // tango:body v=1 screen=login — managed by tango; edit the design on the canvas (Export & Run regenerates this body)
    ZStack(alignment: .topLeading) {
      Button(action: {}) {
        Text("Sign in")
          .font(.system(size: 14, weight: .medium))
      }
        .foregroundColor(Color(red: 0.99216, green: 0.98824, blue: 0.97255, opacity: 1))
        .frame(width: 342, height: 44)
        .background(RoundedRectangle(cornerRadius: 8).fill(Color(red: 0.38039, green: 0.34902, blue: 0.88235, opacity: 1)))
        .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
        .offset(x: 24, y: 700)
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(red: 0.96078, green: 0.93333, blue: 0.87843, opacity: 1))
    .clipped()
  }
}

#Preview {
  LoginScreen()
}
