// Generated by tango — DO NOT EDIT.
// tango:generated v=1 screen=support
// Regenerated on every "Export & Run"; change the design in tango instead.

import SwiftUI

extension Color {
  /// sRGB color from 0–255 channels — emitted by tango's deterministic codegen.
  init(tangoR r: Int, g: Int, b: Int, a: Double) {
    self.init(
      .sRGB,
      red: Double(r) / 255.0,
      green: Double(g) / 255.0,
      blue: Double(b) / 255.0,
      opacity: a
    )
  }
}
