// Generated by tango — DO NOT EDIT.
// tango:generated v=1 screen=dashboard
// Regenerated on every "Export & Run"; change the design in tango instead.

import SwiftUI

/// Dashboard — 390×844
struct TangoDashboardScreen: View {
  var body: some View {
    ZStack(alignment: .topLeading) {
      Text("Dashboard")
        .font(.system(size: 24, weight: .semibold, design: .serif))
        .foregroundColor(Color(tangoR: 10, g: 18, b: 53, a: 1))
        .frame(width: 342, height: 40, alignment: .topLeading)
        .offset(x: 24, y: 60)
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(tangoR: 245, g: 238, b: 224, a: 1))
    .clipped()
  }
}

#Preview {
  TangoDashboardScreen()
}
