// Generated by tango — DO NOT EDIT.
// tango:generated v=1 screen=login
// Regenerated on every "Export & Run"; change the design in tango instead.

import SwiftUI

/// Login — 390×844
struct TangoLoginScreen: View {
  var body: some View {
    ZStack(alignment: .topLeading) {
      Button(action: {}) {
        Text("Sign in")
          .font(.system(size: 14, weight: .medium))
      }
        .foregroundColor(Color(tangoR: 253, g: 252, b: 248, a: 1))
        .frame(width: 342, height: 44)
        .background(RoundedRectangle(cornerRadius: 8).fill(Color(tangoR: 97, g: 89, b: 225, a: 1)))
        .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
        .offset(x: 24, y: 700)
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(tangoR: 245, g: 238, b: 224, a: 1))
    .clipped()
  }
}

#Preview {
  TangoLoginScreen()
}
