// Generated by tango — DO NOT EDIT.
// tango:generated v=1 screen=index
// Regenerated on every "Export & Run"; change the design in tango instead.

import SwiftUI

/// Root view over every tango-generated screen. Embed this (or the individual
/// screen views) wherever the design should appear.
struct TangoGeneratedRootView: View {
  var body: some View {
    TabView {
      TangoLoginScreen()
        .tabItem { Text("Login") }
      TangoDashboardScreen()
        .tabItem { Text("Dashboard") }
    }
  }
}

#Preview {
  TangoGeneratedRootView()
}
