// Created by tango from the design screen "Kitchen Sink".
// The body below is design-managed (tango:body marker) and is regenerated by
// every Export & Run; the rest of this file is yours.

import SwiftUI

/// Kitchen Sink — 390×844
struct KitchenSinkScreen: View {
  var body: some View {
    // tango:body v=1 screen=kitchen-sink — managed by tango; edit the design on the canvas (Export & Run regenerates this body)
    ZStack(alignment: .topLeading) {
      Group {
        RoundedRectangle(cornerRadius: 8)
          .fill(LinearGradient(stops: [.init(color: Color(red: 0.38824, green: 0.35686, blue: 1, opacity: 1), location: 0), .init(color: Color(red: 0, green: 0.83137, blue: 1, opacity: 1), location: 1)], startPoint: UnitPoint(x: 0.146, y: 0.146), endPoint: UnitPoint(x: 0.854, y: 0.854)))
          .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(red: 0.82353, green: 0.84314, blue: 0.89804, opacity: 0.6), style: StrokeStyle(lineWidth: 1, dash: [4])))
          .frame(width: 390, height: 200)
          .offset(x: 0, y: 0)
        Text("Welcome \"back\"")
          .font(.system(size: 30, weight: .bold, design: .serif))
          .foregroundColor(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1))
          .frame(width: 342, height: 40, alignment: .topLeading)
          .offset(x: 24, y: 60)
        Text("Line one\nLine two")
          .font(.system(size: 14, weight: .regular))
          .foregroundColor(Color(red: 0.2902, green: 0.32941, blue: 0.44706, opacity: 1))
          .multilineTextAlignment(.center)
          .frame(width: 342, height: 20, alignment: .top)
          .offset(x: 24, y: 104)
        TextField("Email", text: .constant(""))
          .textFieldStyle(.plain)
          .font(.system(size: 14, weight: .regular))
          .padding(.horizontal, 12)
          .frame(width: 342, height: 40)
          .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(red: 0.82353, green: 0.84314, blue: 0.89804, opacity: 1), lineWidth: 1))
          .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
          .offset(x: 24, y: 240)
        TextEditor(text: .constant(""))
          .scrollContentBackground(.hidden)
          .overlay(alignment: .topLeading) {
            Text("Tell us about yourself")
              .font(.system(size: 14, weight: .regular))
              .foregroundColor(Color(red: 0.2902, green: 0.32941, blue: 0.44706, opacity: 1))
              .padding(EdgeInsets(top: 8, leading: 12, bottom: 8, trailing: 12))
              .allowsHitTesting(false)
          }
          .frame(width: 342, height: 96)
          .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(red: 0.82353, green: 0.84314, blue: 0.89804, opacity: 1), lineWidth: 1))
          .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
          .offset(x: 24, y: 296)
        Button(action: {}) {
          Text("Sign in")
            .font(.system(size: 14, weight: .medium))
        }
          .foregroundColor(Color(red: 1, green: 1, blue: 1, opacity: 1))
          .frame(width: 342, height: 44)
          .background(RoundedRectangle(cornerRadius: 8).fill(Color(red: 0.0549, green: 0.48627, blue: 0.4, opacity: 1)))
          .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
          .offset(x: 24, y: 700)
        Button(action: {}) {
          Text("Skip")
            .font(.system(size: 14, weight: .medium))
        }
          .foregroundColor(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1))
          .frame(width: 342, height: 36)
          .offset(x: 24, y: 752)
        Text("New")
          .font(.system(size: 12, weight: .medium))
          .foregroundColor(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1))
          .padding(EdgeInsets(top: 2, leading: 8, bottom: 2, trailing: 8))
          .background(Capsule().fill(Color(red: 0.5451, green: 0.82353, blue: 0.72549, opacity: 1)))
          .frame(width: 66, height: 22, alignment: .center)
          .offset(x: 300, y: 16)
        Rectangle()
          .fill(Color(red: 0.82353, green: 0.84314, blue: 0.89804, opacity: 1))
          .frame(width: 342, height: 1)
          .frame(width: 342, height: 8, alignment: .center)
          .offset(x: 24, y: 420)
        AsyncImage(url: URL(string: "https://example.test/a.png")) { image in
          image.resizable().scaledToFill()
        } placeholder: {
          Color(red: 0.93333, green: 0.90588, blue: 0.85098, opacity: 1)
        }
          .frame(width: 64, height: 64)
          .clipShape(RoundedRectangle(cornerRadius: 8))
          .offset(x: 24, y: 440)
      }
      Group {
        ZStack {
          RoundedRectangle(cornerRadius: 8)
            .fill(Color(red: 0.93333, green: 0.90588, blue: 0.85098, opacity: 0.4))
            .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(red: 0.82353, green: 0.84314, blue: 0.89804, opacity: 1), style: StrokeStyle(lineWidth: 1, dash: [4])))
          Image(systemName: "photo")
            .foregroundColor(Color(red: 0.2902, green: 0.32941, blue: 0.44706, opacity: 1))
        }
          .frame(width: 64, height: 64)
          .offset(x: 100, y: 440)
        Image(systemName: "gearshape")
          .resizable()
          .scaledToFit()
          .foregroundColor(Color(red: 0.03922, green: 0.07059, blue: 0.20784, opacity: 1))
          .frame(width: 24, height: 24)
          .offset(x: 340, y: 60)
      }
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(red: 0.96078, green: 0.93333, blue: 0.87843, opacity: 1))
    .clipped()
  }
}

#Preview {
  KitchenSinkScreen()
}
