// Generated by tango — DO NOT EDIT.
// tango:generated v=1 screen=kitchen-sink
// Regenerated on every "Export & Run"; change the design in tango instead.

import SwiftUI

/// Kitchen Sink — 390×844
struct TangoKitchenSinkScreen: View {
  var body: some View {
    ZStack(alignment: .topLeading) {
      Group {
        RoundedRectangle(cornerRadius: 8)
          .fill(LinearGradient(stops: [.init(color: Color(tangoR: 99, g: 91, b: 255, a: 1), location: 0), .init(color: Color(tangoR: 0, g: 212, b: 255, a: 1), location: 1)], startPoint: UnitPoint(x: 0.146, y: 0.146), endPoint: UnitPoint(x: 0.854, y: 0.854)))
          .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(tangoR: 210, g: 215, b: 229, a: 0.6), style: StrokeStyle(lineWidth: 1, dash: [4])))
          .frame(width: 390, height: 200)
          .offset(x: 0, y: 0)
        Text("Welcome \"back\"")
          .font(.system(size: 30, weight: .bold, design: .serif))
          .foregroundColor(Color(tangoR: 10, g: 18, b: 53, a: 1))
          .frame(width: 342, height: 40, alignment: .topLeading)
          .offset(x: 24, y: 60)
        Text("Line one\nLine two")
          .font(.system(size: 14, weight: .regular))
          .foregroundColor(Color(tangoR: 74, g: 84, b: 114, a: 1))
          .multilineTextAlignment(.center)
          .frame(width: 342, height: 20, alignment: .top)
          .offset(x: 24, y: 104)
        TextField("Email", text: .constant(""))
          .textFieldStyle(.plain)
          .font(.system(size: 14, weight: .regular))
          .padding(.horizontal, 12)
          .frame(width: 342, height: 40)
          .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(tangoR: 210, g: 215, b: 229, a: 1), lineWidth: 1))
          .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
          .offset(x: 24, y: 240)
        TextEditor(text: .constant(""))
          .scrollContentBackground(.hidden)
          .overlay(alignment: .topLeading) {
            Text("Tell us about yourself")
              .font(.system(size: 14, weight: .regular))
              .foregroundColor(Color(tangoR: 74, g: 84, b: 114, a: 1))
              .padding(EdgeInsets(top: 8, leading: 12, bottom: 8, trailing: 12))
              .allowsHitTesting(false)
          }
          .frame(width: 342, height: 96)
          .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(tangoR: 210, g: 215, b: 229, a: 1), lineWidth: 1))
          .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
          .offset(x: 24, y: 296)
        Button(action: {}) {
          Text("Sign in")
            .font(.system(size: 14, weight: .medium))
        }
          .foregroundColor(Color(tangoR: 255, g: 255, b: 255, a: 1))
          .frame(width: 342, height: 44)
          .background(RoundedRectangle(cornerRadius: 8).fill(Color(tangoR: 14, g: 124, b: 102, a: 1)))
          .shadow(color: .black.opacity(0.05), radius: 1, x: 0, y: 1)
          .offset(x: 24, y: 700)
        Button(action: {}) {
          Text("Skip")
            .font(.system(size: 14, weight: .medium))
        }
          .foregroundColor(Color(tangoR: 10, g: 18, b: 53, a: 1))
          .frame(width: 342, height: 36)
          .offset(x: 24, y: 752)
        Text("New")
          .font(.system(size: 12, weight: .medium))
          .foregroundColor(Color(tangoR: 10, g: 18, b: 53, a: 1))
          .padding(EdgeInsets(top: 2, leading: 8, bottom: 2, trailing: 8))
          .background(Capsule().fill(Color(tangoR: 139, g: 210, b: 185, a: 1)))
          .frame(width: 66, height: 22, alignment: .center)
          .offset(x: 300, y: 16)
        Rectangle()
          .fill(Color(tangoR: 210, g: 215, b: 229, a: 1))
          .frame(width: 342, height: 1)
          .frame(width: 342, height: 8, alignment: .center)
          .offset(x: 24, y: 420)
        AsyncImage(url: URL(string: "https://example.test/a.png")) { image in
          image.resizable().scaledToFill()
        } placeholder: {
          Color(tangoR: 238, g: 231, b: 217, a: 1)
        }
          .frame(width: 64, height: 64)
          .clipShape(RoundedRectangle(cornerRadius: 8))
          .offset(x: 24, y: 440)
      }
      Group {
        ZStack {
          RoundedRectangle(cornerRadius: 8)
            .fill(Color(tangoR: 238, g: 231, b: 217, a: 0.4))
            .overlay(RoundedRectangle(cornerRadius: 8).strokeBorder(Color(tangoR: 210, g: 215, b: 229, a: 1), style: StrokeStyle(lineWidth: 1, dash: [4])))
          Image(systemName: "photo")
            .foregroundColor(Color(tangoR: 74, g: 84, b: 114, a: 1))
        }
          .frame(width: 64, height: 64)
          .offset(x: 100, y: 440)
        Image(systemName: "gearshape")
          .resizable()
          .scaledToFit()
          .foregroundColor(Color(tangoR: 10, g: 18, b: 53, a: 1))
          .frame(width: 24, height: 24)
          .offset(x: 340, y: 60)
      }
    }
    .frame(width: 390, height: 844, alignment: .topLeading)
    .background(Color(tangoR: 245, g: 238, b: 224, a: 1))
    .clipped()
  }
}

#Preview {
  TangoKitchenSinkScreen()
}
